name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
permissions:
  contents: read
jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: ${{ matrix.ruby == '2.5' && '2.2.28' || 'latest' }}

      - run: bundle exec rbs collection install
        if: ${{ matrix.ruby >= '3.0' }}

      - run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write # To report GitHub Actions status checks
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
        with:
          ruby-version: "3"
          bundler-cache: true

      - run: bundle exec rubocop --debug

      - uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          VALIDATE_ALL_CODEBASE: "true"
          VALIDATE_RUBY: "false"
          VALIDATE_JSCPD: "false"
          VALIDATE_NATURAL_LANGUAGE: "false"
          VALIDATE_YAML_PRETTIER: "false"
          VALIDATE_TRIVY: "false"
          VALIDATE_BIOME_FORMAT: "false"
          VALIDATE_BIOME_LINT: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
